DROP DATABASE IF EXISTS lab_bdd;
STOP SLAVE;
RESET SLAVE ALL;
SET GLOBAL gtid_slave_pos = '1-1-28';
CHANGE MASTER TO MASTER_HOST='192.168.56.101', MASTER_PORT=3306, MASTER_USER='repl_user', MASTER_PASSWORD='ReplUser_2025!', MASTER_USE_GTID=slave_pos;
START SLAVE;
